from django.db import models

class chimeRoom(models.Model):
    capacity = models.IntegerField()
    floor = models.IntegerField()
    name = models.CharField(max_length=50)
    active = models.BooleanField()
    white_board = models.BooleanField()
    projector = models.BooleanField()
    internet = models.BooleanField()
    wi_fi = models.BooleanField()
    intercom = models.BooleanField()
    tele_conferencing = models.BooleanField()
    video_conferencing = models.BooleanField()
    is_locked = models.BooleanField()

class chimeBooking(models.Model):
    created_dt = models.DateTimeField(auto_now_add=True, blank=False)
    modified_dt = models.DateTimeField(auto_now=True, blank=False)
    room_id = models.IntegerField(null=True)
    meeting_starting = models.DateTimeField()
    meeting_ending = models.DateTimeField()
    user_capacity = models.IntegerField()
    active = models.BooleanField()
    white_board = models.BooleanField()
    projector = models.BooleanField()
    internet = models.BooleanField()
    wi_fi = models.BooleanField()
    intercom = models.BooleanField()
    tele_conferencing = models.BooleanField()
    video_conferencing = models.BooleanField()
    is_locked = models.BooleanField()
